name: myanimelist_api
version: 0.3.0
description: Asynchronous API wrapper for the official MyAnimeList API v2.
repository: https://github.com/rsktg/MyAnimeList-API
dependencies:
  json_annotation: ^4.0.1
  http: ^0.13.3
dev_dependencies:
  effective_dart: ^1.3.1
  json_serializable: ^4.1.2
  build_runner: ^2.0.3
  test: ^1.17.4
environment:
  sdk: '>=2.12.0 <3.0.0'
